config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'libraries#index'

  resources :libraries do
    resources :authors
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :library
end

app/models/library.rb
# frozen_string_literal: true

class Library < ApplicationRecord
  has_many :authors, dependent: :destroy
  # check validation for "name" field, true means validation will be called automatically
  validates :name, length: { minimum: 5 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

class AuthorsController < ApplicationController
  # method to display all authors
  def index
    @authors = Author.all
  end

  # method to add new authors
  def new
    @author = Author.new
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
    redirect_to @author
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])

    @author.destroy
    redirect_to author_path
  end

  def create
    # check for saving author to the database
    # render plain: params[:author].inspect

    # call the model
    @author = Author.new(author_params)

    # save in database
    if @author.save
      # redirect to show method
      redirect_to @author
    else
      render 'edit'
    end
  end

  private

  # allow fields
  def author_params
    params.require(:author).permit(:name, :surname, :country)
  end
end

app/controllers/libraries_controller.rb
# frozen_string_literal: true

class LibrariesController < ApplicationController
  # method to display all libraries
  def index
    @libraries = Library.all
  end

  # method to add new libraries
  def new
    @library = Library.new
  end

  def show
    @library = Library.find(params[:id])
  end

  def edit
    @library = Library.find(params[:id])
    redirect_to @library
  end

  def update
    @library = Library.find(params[:id])

    if @library.update(library_params)
      redirect_to @library
    else
      render 'edit'
    end
  end

  def destroy
    @library = Library.find(params[:id])

    @library.destroy
    redirect_to libraries_path
  end

  def create
    # check for saving libraries to the database
    # render plain: params[:library].inspect

    # call the model
    @library = Library.new(library_params)

    # save in database
    if @library.save
      # redirect to show method
      redirect_to @library
    else
      render 'edit'
    end
  end

  private

  # allow fields
  def library_params
    params.require(:library).permit(:name, :country, :body)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/libraries_helper.rb
# frozen_string_literal: true

module LibrariesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100">
    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <span class="navbar-brand" href="#">Best Libraries on the Internet</span>
          <span class="navbar-brand"><%= link_to "Add Library", new_library_path %></span>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search..." aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>   
    </header>

    <%= yield %>
  </body>
</html>

app/views/libraries/edit.html.erb
<h2>Edit Library</h2>
<%= form_for :library, url: library_path(@library), method: :patch do |f| %>

  <%# below method to showing errors if validation does not work %>

  <% if @library.errors.any? %>
    <% @library.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    Name<br>
    <%= f.text_field :name %>
  </p>

  <p>
    Country Name<br>
    <%= f.text_field :country %>
  </p>

  <p>
    Description<br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/libraries/index.html.erb
<div class="container">
  <h1>All libraries</h1>
  <% @libraries.each do |library| %>
    <div class="alert alert-primary">
      <h2><b><%= library.name %></b></h2>
      <p><%= library.country %>
      <p><%= library.body %>
      <%= link_to "Читать далее",library_path(library), :class => 'btn btn-outline-dark' %>
    </div>
  <% end %>
</div>

app/views/libraries/new.html.erb
<h2>Add new library</h2>
<%= form_for :library, url: libraries_path do |f| %>

  <%# below method to showing errors if validation does not work  %>

  <% if @library.errors.any? %>
    <% @library.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    Name<br>
    <%= f.text_field :name %>
  </p>

  <p>
    Country Name<br>
    <%= f.text_field :country %>
  </p>

  <p>
    Description<br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/libraries/show.html.erb
<h1><b><%= @library.name %></b></h1>
<p><%= @library.country %></p>
<p><%= @library.body %></p>
<%= link_to "Редактировать", edit_library_path(@library), :class => 'btn btn-warning' %>
<%= link_to "Удалить", library_path(@library), method: :delete, :class => 'btn btn-danger' %>